version: '3.8'

services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    volumes:
      - ./glance.yml:/app/config/glance.yml:ro
    ports:
      - 8280:8080
    restart: unless-stopped
